- name: Installs MariaDB mySQL 
  hosts: mongodb-servers
  become: true
  become_user: root
  roles:
    - role: mariadb
  vars:
      mariadb_custom_cnf:
        mysqld:
           general-log:
           general-log-file: queries.log
           log-output: file
  # load AWS variables from this group vars file
  vars_files:
      - ../inventory/dev/group_vars/mariadb-servers

  tasks:
      - add_host: name=localhost
                  groups=dev
