---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat-servers
  remote_user: ansible
  become: yes
  become_method: sudo
  roles:
#    - selinux
    - tomcat8
# load AWS variables from this group vars file
  vars_files:
      - ../inventory/dev/group_vars/tomcat-servers
  tasks:
      - add_host: name=localhost
                  groups=dev
