# roles/mariadb/tasks/install.yml
---
- name: Add mariadb repo
  yum_repository:
    name: mariadb
    description: mariadb
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: 1
    enabled: 1
  tags: mariadb

- name: Install MariaDB packages
  yum: name={{ item }} state=installed 
  update_cache: yes
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python
  tags: mariadb

