- name: Install MongoDB
  hosts: mongodb-servers
  become: true
  become_user: root
  roles:
    - role: mongo
  # load AWS variables from this group vars file
  vars_files:
      - ../inventory/dev/group_vars/mongodb-servers

  tasks:
      - add_host: name=localhost
                  groups=dev
